# Generated by Django 4.2.1 on 2023-05-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='ob',
        ),
    ]
