# Generated by Django 4.2.1 on 2023-05-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0002_rename_file_file_ob'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
